config/routes.rb
Rails.application.routes.draw do

  get 'settings/', to: "settings#index", as: "settings"

 

  devise_for :users

  resources :companies

  resources :employee_departments do
  	resources :employees
  end

  resources :work_orders

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	acts_as_paranoid
	
	validates :name, presence: true
	validates :email, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
	acts_as_paranoid
	
	belongs_to :employee_department
end

app/models/employee_department.rb
class EmployeeDepartment < ApplicationRecord
	acts_as_paranoid
	
	has_many :employees

	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :find_company, only: [:show, :edit, :update, :destroy]

  def index
  	@companies = Company.all
  end

  def new
  	@company = Company.new
  end

  def create
  	@company = Company.new(company_params)
  	@companies = Company.all
  	render action: 'new' and return unless @company.save
  end

  def edit
  end

  def update
    @companies = Company.all
  	render action: 'edit' and return unless @company.update(company_params)
  end

  def destroy
    @company.destroy
  end

  private
  def find_company
  	@company = Company.find(params[:id])
  end

  def company_params
  	params.require(:company).permit(:id, :name, :address, :website, :email, :phone, :mobile, :fax)
  end
end

app/controllers/employee_departments_controller.rb
class EmployeeDepartmentsController < ApplicationController
	before_filter :find_employee_department, only: [:show, :edit, :update, :destroy]

  def index
  	@employee_departments = EmployeeDepartment.all
  end

  def new
  	@employee_department = EmployeeDepartment.new
  end

  def create
  	@employee_department = EmployeeDepartment.new(employee_department_params)
  	@employee_departments = EmployeeDepartment.all
  	render action: 'new' and return unless @employee_department.save
  end

  def edit
  end

  def update
  	@employee_departments = EmployeeDepartment.all
  	render action: 'edit' and return unless @employee_department.update(employee_department_params)
  end

  def destroy
  	@employee_department.destroy
  end

  private
  def find_employee_department
  	@employee_department = EmployeeDepartment.find(params[:id])
  end

  def employee_department_params
  	params.require(:employee_department).permit(:id, :name, :active)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :find_employee, only: [:show, :edit, :update, :destroy]

  def index
  	@employees = Employee.all
  end

  def new
    @employee_department = EmployeeDepartment.find(params[:employee_department_id])
  	@employee = Employee.new
  end

  def create
  	@employee = Employee.new(employee_params)
  	@employees = Employee.all
  	render action: 'new' and return unless @employee.save
  end

  def edit
    @employee_department = EmployeeDepartment.find(params[:employee_department_id])
  end

  def update
  	@employees = Employee.all
  	render action: 'edit' and return unless @employee.update(employee_params)
  end

  def destroy
  	@employee.destroy
  end

  private
  def find_employee
  	@employee = Employee.find(params[:id])
  end

  def employee_params
  	params.require(:employee).permit(:id, :first_name, :last_name, :address_line_1, :email, :phone, :mobile, :employee_department_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
  def index
  	@users = User.all.count
  	@companies = Company.all.count
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  def index
  	@work_orders = WorkOrder.all
  end

  def new
  	@work_order = WorkOrder.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employee_departments_helper.rb
module EmployeeDepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/companies/_company.html.erb
<tr>
  <th scope="row"><%= company.id %></th>
  <td><%= company.name %></td>
  <td><%= company.address %></td>
  <td><%= company.website %></td>
  <td><%= company.phone %></td>
  <td>
  	<%= link_to "Edit", edit_company_path(company), class:"btn btn-md btn-warning", remote: true  %>
  	<%= link_to "Delete", company_path(company), class: "btn btn-md btn-danger", remote: true, method: :delete %>  	
  </td>
</tr>

app/views/companies/_edit.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Edit Company</h4>
        </div>
        <%= render 'companies/form' %>
    </div>
</div>

app/views/companies/_form.html.erb
<%= form_for @company, remote: true do |f| %>
<div class="modal-body">
	<% if @company.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<% @company.errors.full_messages.each do |e| %>
				<%= e %><br />
			<% end %>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :name, class: "label-control" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :address, class: "label-control" %>
		<%= f.text_area :address, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :website, class: "label-control" %>
		<%= f.text_field :address, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :email, class: "label-control" %>
		<%= f.email_field :email, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :phone, class: "label-control" %>
		<%= f.phone_field :phone, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :mobile, class: "label-control" %>
		<%= f.phone_field :mobile, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :fax, class: "label-control" %>
		<%= f.phone_field :fax, class: "form-control" %>
	</div>
                
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= f.submit "Save", class: "btn btn-primary-outline" %>
</div>
<% end %>

app/views/companies/_new.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">New Company</h4>
        </div>
        <%= render 'companies/form' %>
    </div>
</div>

app/views/companies/create.js.erb
$("#myModal").modal("hide");
$("table#companies-table").html("<%= j render @companies %>");

app/views/companies/destroy.js.erb
$('th[scope="row"]:contains("<%= @company.id %>")').parent("tr").remove();

app/views/companies/edit.js.erb
$("#myModal").html('<%= j(render partial: "companies/edit", locals: {company: @company}) %>')
$("#myModal").modal("show")

app/views/companies/index.html.erb
<div class="row">
	<h2>Companies</h2>
</div>
<div class="row">
	<table id="companies-table" class="table">
	  <thead class="thead-inverse">
	    <tr>
	      <th>#</th>
	      <th>Name</th>
	      <th>Address</th>
	      <th>Username</th>
	      <th>Phone</th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
	  <% @companies.each do |company| %>
	    <%= render 'companies/company', company: company %>
	  <% end %>
	  </tbody>
	</table>
	<%= link_to "New company", new_company_path, remote: true, class: "btn btn-md btn-primary" %>
</div>

app/views/companies/new.js.erb
$("#myModal").html('<%= j(render partial: "companies/new", locals: {company: @company}) %>')
$("#myModal").modal("show")

app/views/companies/update.js.erb
$("#myModal").modal("hide");
$("table#companies-table").html("<%= j render @companies %>");

app/views/employee_departments/_edit.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Edit Department</h4>
        </div>
        <%= render 'employee_departments/form' %>
    </div>
</div>

app/views/employee_departments/_employee_department.html.erb
<div class="col-sm-3">	
  <div class="card card-block">
    <h3 class="card-title"><%= employee_department.name %></h3>
    <p class="card-text">Employees: <%= employee_department.employees.count %></p>
    <%= link_to "Employees", employee_department_employees_path(employee_department), class: "btn btn-md btn-warning pull-md-left" %>
    <%= link_to "Edit", edit_employee_department_path(employee_department), remote: true, class: "btn btn-md btn-info pull-md-right" %>
  </div>
</div>

app/views/employee_departments/_form.html.erb
<%= form_for @employee_department, remote: true do |f| %>
<div class="modal-body">
	<% if @employee_department.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<% @employee_department.errors.full_messages.each do |e| %>
				<%= e %><br />
			<% end %>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :name, class: "label-control" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>	
	<div class="form-group">
		<%= f.label :active, class: "label-control" %>
		<%= f.check_box :active, class: "form-control" %>
	</div>
                
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= f.submit "Save", class: "btn btn-primary-outline" %>
</div>
<% end %>

app/views/employee_departments/_new.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">New Department</h4>
        </div>
        <%= render 'employee_departments/form' %>
    </div>
</div>

app/views/employee_departments/create.js.erb
$("#myModal").modal("hide");
$("div#employee-departments-container").html("<%= j render @employee_departments %>");

app/views/employee_departments/edit.js.erb
$("#myModal").html('<%= j(render partial: "employee_departments/edit", locals: {employee_department: @employee_department}) %>')
$("#myModal").modal("show")

app/views/employee_departments/index.html.erb
<div class="row">
	<h2>Departments</h2>
	<%= link_to "Create", new_employee_department_path, class: "btn btn-md btn-primary", remote: true %>
</div>
<br />
<div class="row" id="employee-departments-container">
	<% @employee_departments.each do |employee_department| %>
		<%= render 'employee_departments/employee_department', employee_department: employee_department %>
	<% end %>
</div>

app/views/employee_departments/new.js.erb
$("#myModal").html('<%= j(render partial: "employee_departments/new", locals: {department: @employee_department}) %>')
$("#myModal").modal("show")

app/views/employee_departments/update.js.erb
$("#myModal").modal("hide");
$("div#employee-departments-container").html("<%= j render @employee_departments %>");

app/views/employees/_edit.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Edit Employee</h4>
        </div>
        <%= render 'employees/form' %>
    </div>
</div>

app/views/employees/_employee.html.erb
<tr>
  <th scope="row"><%= employee.id %></th>
  <td><%= employee.first_name %></td>
  <td><%= employee.last_name %></td>
  <td><%= employee.address_line_1 %></td>
  <td><%= employee.phone %></td>
  <td>
  	<%= link_to "Edit", edit_employee_department_employee_path(params[:employee_department_id], employee), class:"btn btn-md btn-warning", remote: true  %>
  	<%= link_to "Delete", employee_department_employee_path(params[:employee_department_id], employee), class: "btn btn-md btn-danger", remote: true, method: :delete %>  	
  </td>
</tr>

app/views/employees/_form.html.erb
<%= form_for [@employee_department, @employee], remote: true do |f| %>
<div class="modal-body">
	<% if @employee.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<% @employee.errors.full_messages.each do |e| %>
				<%= e %><br />
			<% end %>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :first_name, class: "label-control" %>
		<%= f.text_field :first_name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :last_name, class: "label-control" %>
		<%= f.text_field :last_name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :address_line_1, class: "label-control" %>
		<%= f.text_area :address_line_1, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :email, class: "label-control" %>
		<%= f.email_field :email, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :phone, class: "label-control" %>
		<%= f.phone_field :phone, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :mobile, class: "label-control" %>
		<%= f.phone_field :mobile, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :employee_department_id, class: "label-control" %>
		<%= f.collection_select :employee_department_id, EmployeeDepartment.where(active: true), :id, :name, {}, class: "select2" %>
	</div>
                
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= f.submit "Save", class: "btn btn-primary-outline" %>
</div>
<% end %>

app/views/employees/_new.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">New Employee</h4>
        </div>
        <%= render 'employees/form' %>
    </div>
</div>

app/views/employees/create.js.erb
$("#myModal").modal("hide");
$("table#employees-table").html("<%= j render @employees %>");

app/views/employees/destroy.js.erb
$('th[scope="row"]:contains("<%= @employee.id %>")').parent("tr").remove();

app/views/employees/edit.js.erb
$("#myModal").html('<%= j(render partial: "employees/edit", locals: {employee: @employee}) %>')
$("#myModal").modal("show")

app/views/employees/index.html.erb
<div class="row">
	<h2>Employees</h2>
</div>
<div class="row">
	<table id="employees-table" class="table">
	  <thead class="thead-inverse">
	    <tr>
	      <th>#</th>
	      <th>First name</th>
	      <th>Last name</th>
	      <th>Address</th>
	      <th>Phone</th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
	  <% @employees.each do |employee| %>
	    <%= render 'employees/employee', employee: employee %>
	  <% end %>
	  </tbody>
	</table>
	<%= link_to "New Employee", new_employee_department_employee_path(params[:employee_department_id]), remote: true, class: "btn btn-md btn-primary" %>
</div>

app/views/employees/new.js.erb
$("#myModal").html('<%= j(render partial: "employees/new", locals: {employee: @employee}) %>')
$(".select2" ).select2({});
$("#myModal").modal("show")

app/views/employees/update.js.erb
$("#myModal").modal("hide");
$("table#employees-table").html("<%= j render @employees %>");

app/views/home/_circle_panel.html.erb
<div class="row placeholders">
    <div class="col-xs-6 col-sm-3 placeholder text-xs-center">
        <img src="//placehold.it/200/dddddd/fff?text=1" class="center-block img-responsive img-circle" alt="Generic placeholder thumbnail">
        <h4>Responsive</h4>
        <span class="text-muted">Device agnostic</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder text-xs-center">
        <img src="//placehold.it/200/e4e4e4/fff?text=2" class="center-block img-responsive img-circle" alt="Generic placeholder thumbnail">
        <h4>Frontend</h4>
        <span class="text-muted">UI / UX oriented</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder text-xs-center">
        <img src="//placehold.it/200/d6d6d6/fff?text=3" class="center-block img-responsive img-circle" alt="Generic placeholder thumbnail">
        <h4>HTML5</h4>
        <span class="text-muted">Standards-based</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder text-xs-center">
        <img src="//placehold.it/200/e0e0e0/fff?text=4" class="center-block img-responsive img-circle" alt="Generic placeholder thumbnail">
        <h4>Framework</h4>
        <span class="text-muted">CSS and JavaScript</span>
    </div>
</div>

app/views/home/_infos_panel.html.erb
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="card card-inverse card-success">
            <div class="card-block bg-success">
                <div class="rotate">
                    <i class="fa fa-user fa-5x"></i>
                </div>
                <h6 class="text-uppercase">Users</h6>
                <h1 class="display-1"><%= @users %></h1>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="card card-inverse card-danger">
            <div class="card-block bg-danger">
                <div class="rotate">
                    <i class="fa fa-list fa-4x"></i>
                </div>
                <h6 class="text-uppercase">Companies</h6>
                <h1 class="display-1"><%= @companies %></h1>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="card card-inverse card-info">
            <div class="card-block bg-info">
                <div class="rotate">
                    <i class="fa fa-twitter fa-5x"></i>
                </div>
                <h6 class="text-uppercase">Tweets</h6>
                <h1 class="display-1">125</h1>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="card card-inverse card-warning">
            <div class="card-block bg-warning">
                <div class="rotate">
                    <i class="fa fa-share fa-5x"></i>
                </div>
                <h6 class="text-uppercase">Shares</h6>
                <h1 class="display-1">36</h1>
            </div>
        </div>
    </div>
</div>
<!--/row-->

app/views/home/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Large Modal</h4>
            </div>
            <div class="modal-body">
                This is a dashboard layout for Bootstrap 4. This is an example of the Modal component which you can use to show content. Any content can be placed inside the modal and it can use the Bootstrap grid classes.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary-outline" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<h1 class="display-1 hidden-xs-down">
  CRM mini Dashboard
</h1>

<%= render 'infos_panel' %>
<hr>
<%= render 'circle_panel' %>

<%= render 'rest' %>

app/views/settings/index.html.erb
<script>
	$(document).ready(function(){
		$('#calendar').fullCalendar({});
	})
</script>
<!--div class="row">
	<div class="col-md-4">
		<div class="card">
		  <h3 class="card-header">Šifarnici</h3>
		  <div class="card-block">    
		    <p class="card-text">
		    	<div class="list-group">
		    		<%#= link_to "Type", "#", class: "list-group-item" %>
		    	</div>
		    </p>		    
		  </div>
		</div>
	</div>
</div-->


<div class="row">
	<div class="col-md-10">
		<div id="calendar"></div>		
	</div>
</div>

app/views/work_orders/_form.html.erb
<%= form_for @work_order do |f| %>
	<div class="form-group">
		<%= f.label :name, class: "label-control" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :description, class: "label-control" %>
		<%= f.text_area :description, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :start_date, class: "label-control" %>
		<%= f.text_field :start_date, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :end_date, class: "label-control" %>
		<%= f.text_field :end_date, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :whole_day_task, class: "label-control" %>
		<%= f.check_box :whole_day_task, class: "form-control" %>
	</div>
	<div class="form-group pull-md-right">
		<%= link_to "Cancel", work_orders_path, class: "btn btn-md btn-danger" %>
		<%= f.submit "Save", class: "btn btn-md btn-primary" %>
	</div>
<% end %>

app/views/work_orders/_work_order.html.erb
<tr>
	<th scope="row"><%= work_order.id %></th>
	<td><%= work_order.name %></td>
	<td><%= work_order.company.name %></td>
	<td><%= work_order.start_date %></td>
	<td><%= work_order.end_date %></td>
</tr>

app/views/work_orders/index.html.erb
<div class="row">
	<h1>Work Orders</h1>
</div>
<div class="row">
	<table id="work-orders-table" class="table">
	  <thead class="thead-inverse">
	    <tr>
	      <th>#</th>
	      <th>Name</th>
	      <th>Company</th>
	      <th>Start from</th>
	      <th>Ends at</th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @work_orders.each do |work_order| %>
				<%= render 'work_orders/work_order', work_order: work_order %>
	  	<% end %>
	  </tbody>
	</table>
	<%= link_to "New work order", new_work_order_path, class: "btn btn-md btn-primary" %>
</div>

app/views/work_orders/new.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="card">
		  <h3 class="card-header">New Work Order</h3>
		  <div class="card-block">    
		    	<%= render "work_orders/form" %>	    
		  </div>
		</div>
	</div>
</div>