config/routes.rb
Rails.application.routes.draw do

  get 'settings/', to: "settings#index", as: "settings"

 

  devise_for :users

  resources :companies

  resources :employee_departments do
  	resources :employees
  end

  resources :work_orders

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	acts_as_paranoid
	
	validates :name, presence: true
	validates :email, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
	acts_as_paranoid
	
	belongs_to :employee_department
end

app/models/employee_department.rb
class EmployeeDepartment < ApplicationRecord
	acts_as_paranoid
	
	has_many :employees

	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :find_company, only: [:show, :edit, :update, :destroy]

  def index
  	@companies = Company.all
  end

  def new
  	@company = Company.new
  end

  def create
  	@company = Company.new(company_params)
  	@companies = Company.all
  	render action: 'new' and return unless @company.save
  end

  def edit
  end

  def update
    @companies = Company.all
  	render action: 'edit' and return unless @company.update(company_params)
  end

  def destroy
    @company.destroy
  end

  private
  def find_company
  	@company = Company.find(params[:id])
  end

  def company_params
  	params.require(:company).permit(:id, :name, :address, :website, :email, :phone, :mobile, :fax)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :find_employee, only: [:show, :edit, :update, :destroy]

  def index
  	@employees = Employee.all
  end

  def new
    @employee_department = EmployeeDepartment.find(params[:employee_department_id])
  	@employee = Employee.new
  end

  def create
  	@employee = Employee.new(employee_params)
  	@employees = Employee.all
  	render action: 'new' and return unless @employee.save
  end

  def edit
    @employee_department = EmployeeDepartment.find(params[:employee_department_id])
  end

  def update
  	@employees = Employee.all
  	render action: 'edit' and return unless @employee.update(employee_params)
  end

  def destroy
  	@employee.destroy
  end

  private
  def find_employee
  	@employee = Employee.find(params[:id])
  end

  def employee_params
  	params.require(:employee).permit(:id, :first_name, :last_name, :address_line_1, :email, :phone, :mobile, :employee_department_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
  def index
  	@users = User.all.count
  	@companies = Company.all.count
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  def index
  	@work_orders = WorkOrder.all
  end

  def new
  	@work_order = WorkOrder.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employee_departments_helper.rb
module EmployeeDepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmMini</title>
    <%= csrf_meta_tags %>		
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <title>Bootstrap 4 Dashboard</title>
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-dark bg-primary">
    <button class="navbar-toggler hidden-sm-up pull-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        ☰
    </button>
    <a class="navbar-brand" href="#">Navbar</a>
    <div class="collapse navbar-toggleable-xs" id="collapsingNavbar">
    	<% if user_signed_in? %>
        <ul class="nav navbar-nav pull-right">
            <li class="nav-item active">
            	<%= link_to root_path, class: "nav-link" do %>
            		Home <span class="sr-only">Home</span>
            	<% end %>
            </li>
            <li class="nav-item">
            	<%= link_to "Profile", "#", class: "nav-link" %>
            </li>            
            <li class="nav-item">
            	<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>	          
        </ul>
        <% end %>
    </div>
</nav>
<div class="container-fluid" id="main">
    <div class="row row-offcanvas row-offcanvas-left">
    <% if user_signed_in? %>
        <div class="col-md-3 col-lg-2 sidebar-offcanvas" id="sidebar" role="navigation">
            <ul class="nav nav-pills nav-stacked">
                <li class="nav-item"><%= link_to "Companies", companies_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Departments", employee_departments_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Work Orders", work_orders_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Settings", settings_path, class: "nav-link" %></li>
            </ul>
        </div>
        <!--/col-->
     <% end %>

        <div class="col-md-9 col-lg-10 main">
            <!--toggle sidebar button-->
            <p class="hidden-md-up">
                <button type="button" class="btn btn-primary-outline btn-sm" data-toggle="offcanvas"><i class="fa fa-chevron-left"></i> Menu</button>
            </p>

            

            <div class="alert alert-warning fade collapse" role="alert" id="myAlert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <strong>Holy guacamole!</strong> It's free.. this is an example theme.
            </div>
						<%= yield %>

        </div>
        <!--/main col-->
    </div>

</div>
<!--/.container-->
<footer class="container-fluid">
    <p class="text-right small">©2015 Company</p>
</footer>

<%= render 'home/modal' %>

  </body>
</html>